/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_lee_lostfound_nativeJava */

#ifndef _Included_kr_lee_lostfound_nativeJava
#define _Included_kr_lee_lostfound_nativeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_lee_lostfound_nativeJava
 * Method:    resultCompareString
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_kr_lee_lostfound_nativeJava_resultCompareString
(JNIEnv*, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
