/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_lee_lostfound_StringParserWithJNI */

#ifndef _Included_kr_lee_lostfound_StringParserWithJNI
#define _Included_kr_lee_lostfound_StringParserWithJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_lee_lostfound_StringParserWithJNI
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_lee_lostfound_StringParserWithJNI_stringFromJNI
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
